매칭 설문 페이지 마크업 및 스타일 적용
a-daily-diary/ADD.FE pull request #174
Opened 2024-01-08 13:30 UTC by yws1502

## 🔗 연관된 이슈

- close #173 

<br />

## 🗒 작업 목록

- [x] 매칭 설문 페이지 아이콘 추가
- [x] 매칭 설문 페이지 마크업 완료
- [x] 매칭 설문 페이지 스타일 완료
- [x] 매칭 설문 관련 state binding 작업
- [x] 피드백 작성 완료 버튼 클릭 시 submit 이벤트 처리 및 main 페이지로 리다이렉트 처리

<br />

## 🧐 PR Point

- 상대방에 대한 feedback type은 총 4가지가 있습니다.
- 해당 feadback type은 각각 check box로 마크업했으며, 각각 state를 관리하는 것이 rerendering을 줄일 수 있다고 생각합니다. 하지만 서버와의 데이터 통신시 데이터를 편하게 관리하는 것과 서로 관련있는 여러 개의 input들을 관리할 때는 object 형식으로 state를 관리하는 것이 더 편하고 생각하여 4개의 feadback type을 관리하는 state로 feadback type obj라는 변수를 사용하고 있습니다.
- 위와 같은 의견을 어떻게 생각하시나요?

<br />

## 💥 Trouble Shooting
- 해당 작업을 하던 중 발생했던 문제에 대해 작성해주세요.

<br />

## 📸 스크린샷 / 피그마 링크

https://github.com/a-daily-diary/ADD.FE/assets/77317312/3beb223a-d215-4987-b36f-48ee76378f5f

세요.

<br />

## 📚 참고

- 참고한 내용 또는 링크를 입력해주세요.

<br />

## ✅ PR Submit 전 체크리스트

- [x] Merge 하는 브랜치는 `main` 브랜치가 아닙니다.
- [x] 코드에 크리티컬한 `error` 또는 `warning`이 존재하지 않습니다.
- [x] 불필요한 `console`이 존재하지 않습니다.

2024-01-21 08:06 UTC, Bori-github requested changes

2024-01-21 08:06 UTC, Bori-github commented on src/assets/icons/index.ts
> +import SurveyBadIcon from './icon_bad.svg';
p3;
icon 이름에 survey 접두어를 빼도 좋을 것 같아요!

2024-01-21 08:06 UTC, Bori-github commented on src/components/matching/FeedbackTypeCheckbox.tsx
> +        }
p1;
style props를 전달하지 않으면 특정 스타일이 적용되지 않기 때문에 다음과 같이 작성해도 우상님이 의도한 것이 동일하게 적용될 것 같습니다.
다만, style props를 자유도 높게 전달할 것인지 같이 논의해보면 좋을 것 같습니다.

```suggestion
        style={{ 
          ...style, 
          display: 'none', 
        }}
```

2024-01-21 08:06 UTC, Bori-github commented on src/pages/matching/survey/index.tsx
> +  const [feedbackTypeObj, setFeedbackTypeObj] = useState<
p3;
feedbackTypeObj이라는 네이밍 보다는 randomMatchingFeedback, userFeedback 등 다른 네이밍이 좋을 것 같습니다!

네이밍에 'Type', 'Obj'가 포함되는 것이 불필요하다고 생각합니다! 
그래서 네이밍 한 번 더 고민해주시면 좋을 것 같아요!

2024-01-21 08:06 UTC, Bori-github commented on src/pages/matching/survey/index.tsx
> +    isNice: false,
p3;
각 피드백에 대한 네이밍 같이 고민해봐요!
기존 아이콘 네이밍 그대로 따라간 것 같아서요 하하

2024-01-21 08:06 UTC, Bori-github commented on src/pages/matching/survey/index.tsx
> +  const [feedbackMsg, setFeedbackMsg] = useState('');
p3;
되도록 Msg와 같은 단축어 사용하지 않으면 좋을 것 같은데 이 부분도 같이 논의해봐요!

그리고 useState에 일관적으로 타입 작성해주시면 좋을 것 같아요!
`useState<string>('')`

2024-01-21 08:06 UTC, Bori-github commented on src/pages/matching/survey/index.tsx
> +  const [isBan, setIsBan] = useState(false);
p3;
ban 이라는 단어의 의미가 금지인데, '이 사람이랑 전화하지 않을래요.'의 네이밍에 적합하지 않다고 느껴집니다.
단어가 길어지더라도 명확한 의미가 담겼으면 좋겠습니다.

2024-01-21 08:06 UTC, Bori-github commented on src/pages/matching/survey/index.tsx
> +  const onSubmitFeedback = async (event: React.FormEvent<HTMLFormElement>) => {
p1;
form 관련해서는 react-hook-form 적용 부탁드립니다! :)

2024-01-21 08:06 UTC, Bori-github commented on src/pages/matching/survey/index.tsx
> +  const { current: activeStyle } = useRef({
p1;
스타일을 useRef를 사용하지 않아도 충분히 적용할 수 있다고 생각합니다.
checked 시 스타일 적용되는 것으로 수정 부탁드립니다.

2024-01-21 08:06 UTC, Bori-github commented
우상님 해당 PR을 보니 저랑 코딩 스타일이 많이 달라서 요 PR 보면서 컨벤션 같이 논의하는 것도 좋을 것 같아요!

2024-01-23 11:24 UTC, yws1502 commented on src/components/matching/FeedbackTypeCheckbox.tsx
> +        }
!!그렇네요 감사합니다~! 해당 부분 수정하겠습니다 :)

2024-01-23 11:41 UTC, yws1502 commented on src/pages/matching/survey/index.tsx
> +  const [feedbackTypeObj, setFeedbackTypeObj] = useState<
피드백이 여러개의 **타입**으로 나눠져있으며 자료형이 **object** 형식으로 되어 있어 feedbackTypeObj이 직관적이라고 생각했는데, 의도가 잘 전달되지 않은 것 같네요.. 네이밍이 제일 어려운거 같아요 ㅋㅋㅋ 😂

2024-01-23 11:41 UTC, yws1502 commented on src/pages/matching/survey/index.tsx
> +  const [isBan, setIsBan] = useState(false);
매칭 사용자 금지! 라는 의미로 ban으로 네이밍했는데, 많은 의미를 뺀 네이밍이였네요! 수정하겠습니다아~

2024-01-23 11:41 UTC, yws1502 commented on src/pages/matching/survey/index.tsx
> +  const onSubmitFeedback = async (event: React.FormEvent<HTMLFormElement>) => {
넵넵 적용해두겠습니다!

2024-01-23 11:41 UTC, yws1502 commented on src/pages/matching/survey/index.tsx
> +  const { current: activeStyle } = useRef({
checked 속성일 잊고 있었네요! 해당 부분 적용하겠습니다~!

2024-01-29 14:27 UTC, sohyeonAn commented on src/pages/matching/survey/index.tsx
> +  ${theme.fonts.button_02};
p1;
ThemeProvider 를 통해 전달된 theme 객체 사용과 styles 파일을 직접 import 하여 사용하는 theme 객체 사용을 혼용하고 있습니다! ThemeProvider를 통한 스타일로 통일 시켜주세요~
```suggestion
  ${({ theme }) => theme.fonts.button_02};
```

2024-01-29 14:40 UTC, sohyeonAn commented on src/types/matching.ts
> +export type FeedbackType = 'isNice' | 'isFluent' | 'isFun' | 'isBad';
p4;
is 접두사가 들어가는 것으로 boolean 값이라는 사실을 유추할 수 있겠지만 type 정의에서 is를 붙이는 것은 조금 부자연스럽다는 생각도 드네요 🤔

2024-01-30 11:59 UTC, yws1502 commented on src/pages/matching/survey/index.tsx
> +  ${theme.fonts.button_02};
넵! 수정하였습니다

2024-01-30 12:00 UTC, yws1502 commented on src/types/matching.ts
> +export type FeedbackType = 'isNice' | 'isFluent' | 'isFun' | 'isBad';
관련 로직 react hook form 적용으로 변경되었습니다! 이따 회의시간에 변수명 같이 봐주시면 감사하겠습니다 :)

2024-01-30 13:22 UTC, yws1502 commented on src/pages/matching/survey/index.tsx
> +  const [isBan, setIsBan] = useState(false);
수정하였습니다!

[a6c4e16](https://github.com/a-daily-diary/ADD.FE/pull/174/commits/a6c4e16735c8f1d0cb50da08348893c1257ff077)

2024-01-30 13:23 UTC, yws1502 commented
@Bori-github @sohyeonAn
남겨주신 Comment 사항들 해당 커밋으로 처리하였습니다!

[cb6c9c1](https://github.com/a-daily-diary/ADD.FE/pull/174/commits/cb6c9c19b0da43b51dd40ca816db329863807601)

2024-01-30 13:32 UTC, yws1502 commented on src/types/matching.ts
> +export type FeedbackType = 'isNice' | 'isFluent' | 'isFun' | 'isBad';
피드백 주신 대로 수정해봤습니다! 의미가 분리되어 더 명확해진거 같아요.
감사합니다 :)

[378e605](https://github.com/a-daily-diary/ADD.FE/pull/174/commits/378e605fb488a142283a7c6fb49ac249886c3827)

2024-02-01 14:13 UTC, sohyeonAn approved these changes

2024-02-03 06:17 UTC, Bori-github requested changes
p1;
폴더 구조에 대해서 제가 기존에 작성된 방식은 불필요한 폴더 생성을 줄이기 위해서
pages 내에 동적 라우팅이나 url의 뎁스가 추가되지 않는 이상 폴더를 생성하지 않았는데,
우상님의 경우 폴더를 생성한 후 Index.tsx에 코드를 작성했습니다.

요거 논의 필요할 거 같아요!

2024-02-03 06:17 UTC, Bori-github commented on src/types/matching.ts
> +interface FeedbackType {
p3;
네이밍 `MatchingFeedback`으로 수정하면 좋을 것 같습니다!

2024-02-03 06:17 UTC, Bori-github commented on src/types/matching.ts
> +}
p3;
네이밍 수정해봤습니다. 확인부탁드려요!

```suggestion
export interface MatchingFeedbackForm {
  matchingFeedback: MatchingFeedback;
  message: string;
  isBlockedMatching: boolean;
}
```

2024-02-03 06:17 UTC, Bori-github commented on src/components/matching/FeedbackTypeCheckbox.tsx
> +    &:checked + svg {
p1;
checked 일 때 폰트 스타일이 변경되어야 합니다.
피그마 참고 부탁드립니다!

2024-02-03 06:17 UTC, Bori-github commented on src/components/matching/FeedbackTypeCheckbox.tsx
이거는 단순 저의 방식인데요. 만약 제가 이 부분 코드를 작성한다면 다음과 같이 할 것 같습니다.
스타일 상태만 변경되고 기능은 정상동작하지 않으니 양해 부탁드립니다.
제가 기존에 약관 동의 부분에 적용한 코드를 변형한 것이니 `src/components/account/RegisterTerms.tsx` 참고 부탁드립니다!

그리고 FunIcon / inFunny의 단어를 통일하면 좋을 것 같습니다.
Fun/Funny 일관성 있게 작성되면 매치가 쉬울 것 같습니다.

```typescript
import styled from '@emotion/styled';

import type { UseFormRegister } from 'react-hook-form';
import type { MatchingFeedbackForm } from 'types/matching';

import { BadIcon, EngIcon, FunIcon, NiceIcon } from 'assets/icons';
import { colors } from 'constants/styles';

interface FeedbackTypeCheckboxProps {
  register: UseFormRegister<MatchingFeedbackForm>;
}

type MatchFeedbackRegisterName =
  | 'feedbackType.isNice'
  | 'feedbackType.isFluent'
  | 'feedbackType.isFunny'
  | 'feedbackType.isBad';

const FEEDBACK = [
  {
    id: 'isNice',
    icon: <NiceIcon />,
    description: '친절해요',
    isChecked: false,
  },
  {
    id: 'isFluent',
    icon: <EngIcon />,
    description: '영어를 잘해요',
    isChecked: false,
  },
  {
    id: 'isFunny',
    icon: <FunIcon />,
    description: '재밌어요',
    isChecked: false,
  },
  {
    id: 'isBad',
    icon: <BadIcon />,
    description: '불쾌해요',
    isChecked: false,
  },
];

const FeedbackTypeCheckbox = ({ register }: FeedbackTypeCheckboxProps) => {
  return (
    <Container>
      {FEEDBACK.map((feedback) => {
        const { id, icon, description } = feedback;
        const registerName = `feedbackType.${id}` as MatchFeedbackRegisterName;
        return (
          <>
            <CheckboxInput
              type="checkbox"
              id={id}
              {...register(registerName)}
            />
            <CheckboxLabel htmlFor={id}>
              {icon}
              <p>{description}</p>
            </CheckboxLabel>
          </>
        );
      })}
    </Container>
  );
};

export default FeedbackTypeCheckbox;

const Container = styled.div`
  display: grid;
  grid-template-columns: repeat(2, 100px);
  justify-content: center;
  gap: 40px 50px;
  margin-bottom: 60px;
`;

const CheckboxInput = styled.input`
  display: none;

  &:checked + label {
    ${({ theme }) => theme.fonts.headline_04};
    color: ${({ theme }) => theme.colors.primary_00};
  }

  &:checked + label > svg {
    outline: 2px solid ${colors.primary_00};
    border-radius: 100%;
  }
`;

const CheckboxLabel = styled.label`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 6px;
  ${({ theme }) => theme.fonts.body_04};
  color: ${({ theme }) => theme.colors.gray_00};
  cursor: pointer;
`;

```

2024-02-05 11:43 UTC, yws1502 commented on src/types/matching.ts
> +}
감사합니다~! 변수명 짓는거 너무 어렵네요 😂

2024-02-05 11:44 UTC, yws1502 commented on src/components/matching/FeedbackTypeCheckbox.tsx
> +    &:checked + svg {
!! 놓친 부분 찾아주셔서 감사합니다 :)

2024-02-05 11:46 UTC, yws1502 commented on src/components/matching/FeedbackTypeCheckbox.tsx
친절하게 코드까지 첨부해주셔서 감사합니다~!

첨부 주신 코드 보면서 리펙토링해볼게요!

2024-02-10 06:55 UTC, yws1502 commented on src/types/matching.ts
> +}
`MatchingFeedback`이라는 변수명은 피드백 유형이라는 의미 보다 조금 더 넓은 의미를 갖는다고 생각해, `FeedbackType`으로 하였습니다!

해당 변수명을 제외하고는 의견주신 네이밍으로 반영했습니다. 의견주셔서 감사합니다!

작업 커밋 : 1c0bd0ecfecbf617282d474041f2d986dae29ad2

2024-02-10 06:58 UTC, yws1502 commented on src/components/matching/FeedbackTypeCheckbox.tsx
위에서 커맨트 주신 내용과 함께 첨부해주신 코드 참고하여 리팩토링 진행하였습니다!

리뷰해주신 덕분에 코드가 더 깔끔해진 것 같네요. 감사합니다!

작업 커밋 : 4ba5a545219bbb0bc12aa7204b0623e8a611298e

2024-02-12 11:11 UTC, yws1502 commented
pages내 폴더 구조 정리에 대한 작업은 별도의 PR로 히스토리를 남길 필요가 없다고 생각하여, 해당 PR에서 같이 작업하였습니다.

작업 커밋 : e91659775606dddd2257cee5e538f310d03ecce3

2024-02-12 13:16 UTC, Bori-github commented on src/components/matching/FeedbackTypeCheckbox.tsx
> +          </Label>
p1;
label에 htmlFor 추가 부탁드립니다.
그리고 label이 inline 레벨이라 내부에 block 레벨인 p태그가 포함되는 것이 적절하지 않습니다.
p태그를 제거해도 좋을 것 같습니다.

```suggestion
          <Fragment key={id}>
            <input type="checkbox" {...hookFormProps} />
            <Label htmlFor={id}>
              {icon}
              {description}
            </Label>
          </Fragment>
```

요렇게 하면 `input:checked` 일 때 스타일 적용이 조금 더 간단해질 것 같습니다!

2024-02-12 13:16 UTC, Bori-github commented on src/components/matching/FeedbackTypeCheckbox.tsx
> +  const { current: FEEDBACK } = useRef([
ask;
이렇게 useRef로 적용한 사례를 처음봤는데 혹시 참고한 코드나 링크 있을까요?
저는 useRef를 사용할 필요가 없다고 생각하는데, useRef를 사용한 이유가 궁금합니다.

2024-02-12 13:16 UTC, Bori-github commented on src/components/matching/FeedbackTypeCheckbox.tsx
> +      outline: 2px solid ${({ theme: { colors } }) => colors.primary_00};
p3;
`${({ theme: { colors } }) => colors.primary_00}` 요렇게 작성해주신거 반대하지는 않은데 코드가 일관되게 작성되었으면 하는 마음에.. 수정 부탁드립니다!
```suggestion
      outline: 2px solid ${({ theme }) => theme.colors.primary_00};
```

2024-02-12 13:16 UTC, Bori-github commented on src/pages/matching/survey.tsx
> +  const isBlockedMatching = useWatch({
useWatch 한 번도 안써봤는데 신기하네요!

2024-02-12 13:16 UTC, Bori-github commented on src/pages/matching/survey.tsx
> +          <CheckBoxLabel>
p1;
label에 htmlFor, input에 id 속성 넣어주세요!

2024-02-12 13:49 UTC, yws1502 commented on src/components/matching/FeedbackTypeCheckbox.tsx
> +          </Label>
빈태그인 경우 key props를 넣을 수 없다고 생각했는데 Fragment 태그를 사용하면 되었네요!
감사합니다 오늘도 배워갑니다!!

아래의 p3, p1 커맨트도 해당 커밋에서 작업하였습니다!
작업 커밋 : eda74e036119a3668ba3399dd1abdccee02b2eb8

2024-02-12 14:20 UTC, yws1502 commented on src/components/matching/FeedbackTypeCheckbox.tsx
> +  const { current: FEEDBACK } = useRef([
개인적으로 tsx 파일 안에는 최대한 컴포넌트 변수만 선언하는 것이 가독성이 좋다고 생각하여 컴포넌트에서 단독으로 사용되는 변수는 내부에서 선언하는 것을 선호하기 때문입니다.

useRef를 사용한 이유는 내부에서 선언된 변수가 state 변경 됨에 따라 계속 할당되는 것을 방지하기 위해 메모이제이션하기 위함입니다.

그리고 질문하시기 전까지 위와 같은 방식을 선호한 다른 이유 중에 컴포넌트 내부에 변수를 선언하는 것이 메모리 측면에서 더 낫다고 생각을 하였는데, 자료를 찾아보니 내부, 외부 똑같이 가비지 컬랙션이 제대로 동작한다는 사실을 알게 되었습니다!

[참고 링크](https://velog.io/@apparatus1/React%EC%97%90%EC%84%9C-%EC%A0%84%EC%97%AD%EC%97%90-%EB%B3%80%EC%88%98%EB%A5%BC-%EC%84%A0%EC%96%B8%ED%95%98%EB%A9%B4-%EC%A0%9C%EB%8C%80%EB%A1%9C-Garbage-Collection-%EB%90%A0%EA%B9%8C#4-%EC%A0%95%EB%A6%AC)

2024-02-12 14:43 UTC, Bori-github commented on src/components/matching/FeedbackTypeCheckbox.tsx
> +  const { current: FEEDBACK } = useRef([
메모리 쪽 항상 잘 놓치는데 우상님 덕분에 저도 배웁니다!

저는 useRef에 적용한 코드가 상수라고 생각했기 때문에 useRef의 사용 여부에 대해 의문이 있었는데요.
해당 컴포넌트에서 register를 prop으로 넘기다보니 우상님께서 useRef를 사용하게 된 부분도 있지 않나 생각이 듭니다. 
useFormContext 사용해서 register를 prop으로 넘기지 않고, useRef 없이 상수화한다면 컴포넌트 외부에서 변수 선언하여 우상님께서 기대하는 메모리 효율을 얻을 수 있지 않을까 생각합니다!

일단 해당 PR은 승인하고 우상님 편한 방식으로 진행하시죠!

2024-02-12 14:43 UTC, Bori-github approved these changes

2024-02-15 12:20 UTC, merged