비밀번호 찾기 페이지 마크업 및 스타일링
a-daily-diary/ADD.FE pull request #182
Opened 2024-02-04 08:28 UTC by sohyeonAn

## 🔗 연관된 이슈

- close #179 

<br />

## 🗒 작업 목록

- [x] 로그인 > 비밀번호 찾기 버튼 UI
- [x] 로그인 > 비밀번호 찾기 버튼 클릭 시 비밀번호 찾기 페이지로 이동
- [x] 비밀번호 찾기 페이지 UI

<br />

## 🧐 PR Point

- 로그인 폼 하단 '비밀번호를 잊으셨나요?' 버튼 추가
- 비밀번호 찾기 페이지 마크업 및 스타일링 구현 (비밀번호 찾기 > 링크 전송, 비밀번호 재설정 UI 는 따로 작업할 예정입니다)

---

- 해당 PR 은 스타일링과 마크업만 진행되었습니다. 기능적인 부분(이메일 형식 검사 및 api 연동 등등) 은 따로 진행될 예정입니다. 
- 따라서, ui를 확인하기 위해 필요한 최소한의 react-form 을 연결했으며 register 컴포넌트를 참고하였기 때문에 RegisterForm type을 그대로 사용한 상태 입니다.  해당 부분은 기능 구현 시 교체될 예정입니다. (`@todo` 로 표시해두었습니다)

<br />

## 💥 Trouble Shooting
- 해당 작업을 하던 중 발생했던 문제에 대해 작성해주세요.

<br />

## 📸 스크린샷 / 피그마 링크
스크린샷 | 
-- |
![Feb-04-2024 17-26-04](https://github.com/a-daily-diary/ADD.FE/assets/23066745/77a0408a-2370-4843-a930-6390b7fe0417) |

<br />

## 📚 참고

- 참고한 내용 또는 링크를 입력해주세요.

<br />

## ✅ PR Submit 전 체크리스트

- [x] Merge 하는 브랜치는 `main` 브랜치가 아닙니다. 
- [x] 코드에 크리티컬한 `error` 또는 `warning`이 존재하지 않습니다.
- [x] 불필요한 `console`이 존재하지 않습니다.

2024-02-04 08:48 UTC, Bori-github requested changes

2024-02-04 08:48 UTC, Bori-github commented on src/pages/account/findPassword.tsx
> +            링크를 이메일로 보내드릴게요.`}
p3;
개행 문자 넣어주시거나 `br` 태그 사용하면 좋을 것 같습니다!

```suggestion
          {`이메일 주소를 입력하면 암호를 재설정할 수 있는\n링크를 이메일로 보내드릴게요.`}
```

2024-02-04 08:48 UTC, Bori-github commented on src/pages/account/findPassword.tsx
> +  z-index: ${Z_INDEX.dialog};
p1;
`position` 속성 없이 `z-index` 사용은 지양해주시면 좋을 것 같습니다!
`position` 속성 추가 부탁드려요!

2024-02-04 08:48 UTC, Bori-github commented on src/pages/account/findPassword.tsx
> +
ask;
소현님 혹시 스타일 코드에 개행을 넣는 기준이 있으신가요?
궁금해서 질문 드립니다!

2024-02-04 08:48 UTC, Bori-github commented on src/pages/account/login.tsx
> +      <UnderlinedButton
p1;
button 대신 Link 컴포넌트 사용해주시면 좋을 것 같아요!
기능이 페이지 이동이라 Link 사용이 더 적절해보입니다!

2024-02-04 09:17 UTC, sohyeonAn commented on src/pages/account/findPassword.tsx
> +            링크를 이메일로 보내드릴게요.`}
저는 개행이 있으면 코드에서 보여지는 그대로 화면에도 보여지는 것을 선호해서 `white-space: pre-line` 속성을 썼었는데
한 줄 정도는 `br` 태그 사용으로 변경해도 지저분해 보이지 않는 것 같아 변경하였습니다!

2024-02-04 09:22 UTC, sohyeonAn commented on src/pages/account/findPassword.tsx
> +
저도 기준을 정해놓고 딱 지키는 건 아니지만, 관련 속성끼리 묶는 걸 선호하는 것 같아요. 
폰트는 폰트끼리 레이아웃은 레이아웃(padding, margin...) 끼리, 크기속성 끼리(width, height..), flex 속성 끼리 정도로요.

한 그룹 안에서 폰트는 컬러, 크기, weight..등등 이런 순서로 와야한다 정해놓은 기준은 없습니다.

이 부분도 같이 얘기 나눠서 맞춰나가면 좋겠네요!

2024-02-04 09:23 UTC, sohyeonAn commented on src/pages/account/login.tsx
> +      <UnderlinedButton
말씀주신대로 Link 가 더 적절하겠네요!! 
위에서 리뷰해주신 스타일관련 변경과 함께 한 커밋에서 반영하였습니다 [6e9afaa](https://github.com/a-daily-diary/ADD.FE/pull/182/commits/6e9afaaddf926f284ddfdbe70c30ce78cc443588)

2024-02-04 09:29 UTC, Bori-github commented on src/pages/account/findPassword.tsx
> +            링크를 이메일로 보내드릴게요.`}
저의 경우 최근에는 `\n`나 `br` 태그로 사용하는 것을 선호하게 되었어요!
불필요한 코드를 최소화하는게 가장 좋은 성능 최적화라고 생각해서 가독성을 해치지 않는 선에서 최소화 하려고 하다보니 선호하는 방식이 바뀐 것 같아요.
소현님 의견 남겨주셔서 감사합니다!

2024-02-04 09:30 UTC, Bori-github commented on src/pages/account/findPassword.tsx
> +
네네! 같이 이야기 해봐요!

2024-02-04 09:31 UTC, Bori-github approved these changes

2024-02-08 07:47 UTC, yws1502 approved these changes
고생하셨습니다~!

2024-02-10 11:20 UTC, merged