매칭 타이머 기능 구현
a-daily-diary/ADD.FE pull request #193
Opened 2024-02-12 12:40 UTC by yws1502

## 🔗 연관된 이슈

- close #192

<br />

## 🗒 작업 목록

- [x] 불필요한 로직 제거
- [x] 타이머 기능 구현

<br />

## 🧐 PR Point

- 기존에는 컴포넌트를 사용하는 쪽에서 layout 용 스타일을 적용하였습니다.
    - 해당 부분은 재사용성이 잦은 컴포넌트에서만 적용하는 것으로 보리님과 논의되어 코드 수정하였습니다.
- 커스텀 훅으로 useTimer를 구현하였고, 컴포넌트에서 정의된 커스텀 훅을 호출하여 사용하는 방식으로 구현하였습니다.
    - 작업 커밋: 13d073f2dd15c878a8e1bb127207cc3972d5db48

<br />

## 💥 Trouble Shooting
- 해당 작업을 하던 중 발생했던 문제에 대해 작성해주세요.

<br />

## 📸 스크린샷 / 피그마 링크

https://github.com/a-daily-diary/ADD.FE/assets/77317312/16dbb8f7-316b-4353-b6dd-c60889732ddc

<br />

## 📚 참고

- 참고한 내용 또는 링크를 입력해주세요.

<br />

## ✅ PR Submit 전 체크리스트

- [x] Merge 하는 브랜치는 `main` 브랜치가 아닙니다. 
- [x] 코드에 크리티컬한 `error` 또는 `warning`이 존재하지 않습니다.
- [x] 불필요한 `console`이 존재하지 않습니다.

2024-02-12 13:45 UTC, Bori-github requested changes

2024-02-12 13:45 UTC, Bori-github commented on src/components/matching/MatchingUserInfo.tsx
>    strong {
ask;
우상님 저의 저번에 논의 했을 때 스타일 작성하는 방법 논의만 하다가 끝났나여? 기억이 안나네여.. ㅋㅋㅋㅋㅋ

2024-02-12 13:45 UTC, Bori-github commented on src/hooks/common/useTimer.ts
> +  const [totalSecond, setTotalSecond] = useState(0);
p3;
state에 타입 작성 부탁드립니다!

```suggestion
  const [totalSecond, setTotalSecond] = useState<number>(0);
```

2024-02-12 13:45 UTC, Bori-github commented on src/hooks/common/useTimer.ts
> +  const minute = Math.round(totalSecond / 60)
p1;
floor 사용해야할 것 같은데 확인 한 번 부탁드려요!
```suggestion
  const minute = Math.floor(totalSecond / 60)
```

2024-02-14 14:23 UTC, yws1502 commented on src/components/matching/MatchingUserInfo.tsx
>    strong {
논의했던 내용 중 자주 사용하는 컴포넌트에서만 적용하자는 보리님의 의견에 설득되었습니다 ㅋㅋㅋ

2024-02-14 14:26 UTC, yws1502 commented on src/hooks/common/useTimer.ts
> +  const [totalSecond, setTotalSecond] = useState(0);
자꾸 useState에 타입 넣는것 까먹네요 확인해주셔서 감사합니다!! 타입 적용했습니다

작업 커밋 : 1c60d4fba7663e9b21fc83ee24e28fcf97f059f5

2024-02-14 14:28 UTC, yws1502 commented on src/hooks/common/useTimer.ts
> +  const minute = Math.round(totalSecond / 60)
의식의 흐름대로 코딩하다 반올림을 해버렸네요.. ㅎㅎ
발견해주셔서 감사합니다! 해당 부분 수정했습니다!

작업 커밋 : 4c82056e1a060a33535fad994f24b7d8578d21a5

2024-02-18 04:09 UTC, Bori-github approved these changes
수고하셨습니다!

2024-02-18 04:11 UTC, Bori-github commented
@yws1502 
아! 우상님 추가로
`import React from 'react';` React import문 제거 부탁드려요!
React 17버전부터는 작성하지 않아도 되서요!

2024-02-18 05:33 UTC, sohyeonAn approved these changes

2024-02-18 05:33 UTC, sohyeonAn commented on src/components/matching/MatchingUserInfo.tsx
> +  const { minute, second } = useTimer();
p3;

minutes, seconds 로 복수형태로 쓰는 게 더 적절하지 않나 생각됩니다만 이해하는 데 무리가 없으니 동의하시면 반영해주세요!

2024-02-25 07:36 UTC, yws1502 commented
> @yws1502 아! 우상님 추가로 `import React from 'react';` React import문 제거 부탁드려요! React 17버전부터는 작성하지 않아도 되서요!

@Bori-github @sohyeonAn 
보리님께서 리뷰해주셨던 react import문 제거, 소현님께서 리뷰해주신 시간 변수명 복수형 반영했습니다!


import 제거 작업 커밋: eaf45a4e7437b23c6c0b9af7537bea34e672299c
시간 변수명 복수형 반영 커밋: a349887f581011565d4ab11fea001cf97891c555

2024-02-25 07:36 UTC, merged